### ISSUE TITLE
Dismissing Two Successive Popups Crashes the Device

### ISSUE THREAD

**Issue by SorataYuu** [dbukowski/DBDebugToolkit#11]
After installing DBDebugToolkit, the phone crashes every time two successive popups were created (shown at the same time) and then when dismissing both (one after the other) causes the app to crash. Uninstalling DBDebugToolkit causes the crash not to happen. It is replicable within all scenarios whereby two popups were created and then dismissed.

**Comment by SorataYuu** [comment]
Hello @dbukowski Basically I created two instances of UIAlertController and had both perform present. Then on dismiss of both it crashes. Here's a crash log:

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x18a0ae1c0 __exceptionPreprocess
1  libobjc.A.dylib                0x188ae855c objc_exception_throw
2  CoreFoundation                 0x18a0ae108 -[NSException initWithCoder:]
3  Foundation                     0x18aafed64 NSKVODeallocate
4  libobjc.A.dylib                0x188b01fe0 (anonymous namespace)::AutoreleasePoolPage::pop(void*)
5  CoreFoundation                 0x189f87db8 _CFAutoreleasePoolPop
6  CoreFoundation                 0x18a059b20 __CFRunLoopRun
7  CoreFoundation                 0x189f88048 CFRunLoopRunSpecific
8  GraphicsServices               0x18ba0e198 GSEventRunModal
9  UIKit                          0x18ff732fc -[UIApplication _run]
10 UIKit                          0x18ff6e034 UIApplicationMain
11 OneService                     0x1000a7c6c main (main.m:19)
12 libdispatch.dylib              0x188f6c5b8 (Missing)

**Comment by dbukowski** [comment]
This should be fixed in the new version - v. 0.3.1.
If this problem occurs again, please use crash reports included in the library to provide more details.
