### ISSUE TITLE
will block network request when working with ios9

### ISSUE THREAD

**Issue by rawlinxx** [dbukowski/DBDebugToolkit#15]
i guess maybe something wrong in CLURLProtocol

**Comment by pffan91** [comment]
Same problem :(

**Comment by pffan91** [comment]
Helped         DBDebugToolkit.setNetworkRequestsLoggingEnabled(false)
But this is not the answer, need to fix this somehow :)

**Comment by dbukowski** [comment]
Hi, unfortunately the fix that I made for https://github.com/dbukowski/DBDebugToolkit/issues/2 broke logging network requests on iOS 9. I just released the new version of the library, which stops using that fix on this OS version, so you should be able to update DBDebugToolkit and remove DBDebugToolkit.setNetworkRequestsLoggingEnabled(false) 😉
