### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by Abeansits** [dbukowski/DBDebugToolkit#18]
**What?**
We use Carthage as our dependency manager and would very much like for `DBDebugToolkit` to support it.

**How?**
Supporting Carthage is very easy, I would have opened a PR myself but it seems as if the xcproj is not included in the source code. 
All you basically need to do is share the scheme. More info can be found here: https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by dbukowski** [comment]
Hi! Thanks for the great suggestion, I've been thinking about it for quite some time now. I followed the instructions, you should be able to use `DBDebugToolkit` with Carthage now! Please let me know if you run into any difficulties.
