### ISSUE TITLE
Error: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by bharath-dev** [dbukowski/DBDebugToolkit#20]
I got the following error detail when I tried the library in a Objective C project with deployment target 8.0.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DBDebugToolkit", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

How to overcome this issue ?

**Comment by dbukowski** [comment]
Hi, thanks for reporting this issue! Could you please tell me how exactly are you trying to integrate DBDebugToolkit? Via CocoaPods or Carthage?

**Comment by gaplan** [comment]
via CocoaPods .

**Comment by bharath-dev** [comment]
Welcome, I am integrating via CocoaPods.

**Comment by dbukowski** [comment]
Hi, I’m currently on vacation and I’ll be back in two weeks, but in the meantime I would advise you to take a look at the following links:

https://github.com/CocoaPods/CocoaPods/issues/2545
http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64

It looks like a podfile/project configuration issue. Maybe a simple deep clean or reinstalling the pods would help.

**Comment by dbukowski** [comment]
Did those links help? I think it's more of an issue with the podfile/project configuration, rather than with DBDebugToolkit itself.

**Comment by gamada-de** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem 👍
