### ISSUE TITLE
DBURLProtocol breaks text/event-stream requests

### ISSUE THREAD

**Issue by djMax** [dbukowski/DBDebugToolkit#25]
text/event-stream requests are "chunked" requests with double newline breaks. Because of the way DBURLProtocol intercepts requests, what ends up happening is all response chunks are batched up until the end and then forwarded to the original response handler. Any ideas how to fix this other than disabling interception altogether?

**Comment by djMax** [comment]
This does look related, but not sure how much of it can be adopted.

https://github.com/jivesoftware/JiveLoggingHTTPProtocol/blob/master/Source/JiveLoggingHTTPProtocol/JLHPLoggingHTTPProtocol.m

**Comment by dbukowski** [comment]
Hi, thanks for reporting the issue. Overall, DBDebugToolkit uses `NSURLProtocol` subclass to intercept all the requests. Unfortunately, this implementation has some drawbacks. In this case, I don't have any idea yet how it could be fixed. 

Do you have any small repo where I could see such behavior? Did you check the protocol that you mentioned https://github.com/jivesoftware/JiveLoggingHTTPProtocol and was it working in that case?

For now, I'm labeling this issue with "help wanted".
