### ISSUE TITLE
Weird behavior with URLCache

### ISSUE THREAD

**Issue by felginep** [dbukowski/DBDebugToolkit#31]
There is a weird bug related to custom `URLSession` and `URLCache`.

### Project setup

Here is my `AppDelegate` that enables `DBDebugToolkit`.
```
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

        DBDebugToolkit.setup()

        let window = UIWindow(frame: UIScreen.main.bounds)
        self.window = window
        window.backgroundColor = UIColor.white
        window.rootViewController = ViewController()

        window.makeKeyAndVisible()
        return true
    }
}
```

In my `ViewController`, I have a button that loads an url with `Cache-Control` header set, meaning the system should cache the response.
```
class ViewController: UIViewController {

    private lazy var button: UIButton = {
        let button = UIButton(type: .system)
        button.setTitle("Load", for: .normal)
        button.addTarget(self, action: #selector(load), for: .touchUpInside)
        return button
    }()

    // Custom URLSession with custom cache and custom diskPath
    private lazy var session: URLSession = {
        let memoryCapacity = 500 * 1024 * 1024 // 500 MB
        let diskCapacity = 500 * 1024 * 1024 // 500 MB

        let cache = URLCache(
            memoryCapacity: memoryCapacity,
            diskCapacity: diskCapacity,
            diskPath: "com.xxxxx.yyyyy"
        )

        let configuration = URLSessionConfiguration.default
        configuration.urlCache = cache

        return URLSession(
            configuration: configuration,
            delegate: self,
            delegateQueue: nil
        )
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        view.addSubview(button)
        button.frame = view.bounds
    }

    // MARK: - Private

    @objc private func load() {
        // A ~130 KB image, small enough to be cached by the default URLSession session
        let url = URL(string: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80")!
        session.dataTask(with: url).resume()
    }
}

extension ViewController: URLSessionDataDelegate {

    // MARK: - URLSessionDataDelegate

    func urlSession(_ session: URLSession,
                    dataTask: URLSessionDataTask,
                    willCacheResponse proposedResponse: CachedURLResponse,
                    completionHandler: @escaping (CachedURLResponse?) -> Void) {
        print("session:willCacheResponse:")
        completionHandler(proposedResponse)
    }

    func urlSession(_ session: URLSession,
                    dataTask: URLSessionDataTask,
                    didReceive response: URLResponse,
                    completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
        print("dataTask:didReceive response")
        completionHandler(.allow)
    }

    func urlSession(_ session: URLSession,
                    dataTask: URLSessionDataTask,
                    didReceive data: Data) {
        print("data = \(data)")
    }
}
```

### With DBDebugToolKit activated

When I first clic on the load button, the request is sent to the server, and the logs are the following :
```
dataTask:didReceive response
data = 129408 bytes
```

When I clic a second time, the request is not sent to the server, the cached image is used and the logs are the same.

We can note that the log `print("session:willCacheResponse:")` is never called even it should be.

The cache folder structure is : ![Wrong cache structure](https://i.imgur.com/yLxMKos.png) 

Note the duplication of the `Cache.db` files. What's more the `fsCachedData` folder, that contains the cached image, is at the wrong location. That means the image is saved in the default `URLCache` and not in the custom one I defined in my sesssion.

### Without DBDebugToolKit activated

If I trash the app and remove the line `DBDebugToolkit.setup()` in the `AppDelegate`, when I first clic on the image, the request is sent to the server and the logs are the following:
```
dataTask:didReceive response
data = 16384 bytes
data = 16384 bytes
data = 16384 bytes
data = 16383 bytes
data = 16384 bytes
data = 16384 bytes
data = 16384 bytes
data = 14721 bytes
session:willCacheResponse:
```

Note that this time the logs are correct and `session:willCacheResponse:` is printed !

The cache folder structure is ![Correct cache structure](https://i.imgur.com/GJIRLJE.png)
This time there is only one `Cache.db` file, and the `fsCachedData` folder is under the `com.xxxxx.yyyyy` directory. Which is the expected behavior.

### Issue

So the issue is that a custom url session with a custom url cache is never taken into account with `DBDebugToolkit` activated. What's more the `URLSessionDataDelegate` method `urlSession(_:, dataTask:, willCacheResponse:, completionHandler:)` is not called.

**Comment by felginep** [comment]
Is this resolved ?

**Comment by gamada-de** [comment]
Sorry this is currently not solved. This is an bigger problem of this tool how the request will be currently logged/stored. But i hope this can be fixed in the near future with an refactoring.

**Comment by gamada-de** [comment]
@felginep Maybe you can check if it is now working correct with the new version. [0.9.0](https://github.com/dbukowski/DBDebugToolkit/releases/tag/0.9.0)
