### ISSUE TITLE
Crash Reporting

### ISSUE THREAD

**Issue by mmdock** [dbukowski/DBDebugToolkit#33]
My initial setup for DBDebugToolkit is:

```
let shakeTrigger = DBShakeTrigger()
            DBDebugToolkit.setup(with: [shakeTrigger])
            DBDebugToolkit.setupCrashReporting()
            DBDebugToolkit.addClearDataShortcutItem()
            let clearDefaultsAction = DBCustomAction(name: "Clear User Defaults") {
                DBDebugToolkit.clearUserDefaults()
            }
            DBDebugToolkit.add(clearDefaultsAction)
```

The issue i have: no crash reports are being made.

I have intentionally crashed the app, and even purposefully loaded large images and created OOM errors and there have been no crash logs being logged.  

Did i miss some obvious configuration setup?

**Comment by gamada-de** [comment]
@mmdock Have you test it without debugger?

[See crashreport feature description:](https://github.com/dbukowski/DBDebugToolkit/blob/master/Features.md#crash-reports)
`Also, please note that DBDebugToolkit, just like the other services, cannot report crashes when the app is running under the debugger.`

**Comment by mmdock** [comment]
@gamada-de  wow what a throw back.  yeah, i went to, just now, re-implement this in my app for some debugging reasons and encountered this again.  And yes, no debugger
