### ISSUE TITLE
Exception: "UISearchDisplayController is no longer supported on iOS 13

### ISSUE THREAD

**Issue by hiennvominext** [dbukowski/DBDebugToolkit#36]
I tried to integrate this toolkit into my project (supported from iOS 13) and I got this crash when I chose the Network.  
Thread 1: Exception: "UISearchDisplayController is no longer supported when linking against this version of iOS. Please migrate your application to UISearchController."

**Comment by gamada-de** [comment]
@hiennvominext We have fix this bug in version 0.5.2.
