### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by Max-Job** [dbukowski/DBDebugToolkit#37]
I don’t understand how this could happen. maybe you have any ideas?

![image](https://user-images.githubusercontent.com/58559377/84650033-3151bf80-af10-11ea-8eb0-f1ecb971066a.png)

**Comment by gamada-de** [comment]
@Max-Job A sample app would be needed here to speed up diagnosis.

**Comment by Max-Job** [comment]
I have found a reason. Such a bug occurs due to the intercom button. I had to hide it in the debug.
If anyone has a solution, feel free to write to me about it.

**Comment by gamada-de** [comment]
Maybe it is a problem of your app configuration. I have tested it with the intercom button and it looks ok, so i close the issue.
