### ISSUE TITLE
Unable to pull latest version of pod

### ISSUE THREAD

**Issue by ankykush** [dbukowski/DBDebugToolkit#38]
In cocoapods.org when I search for DBDebugToolKit Pod it shows version 0.5.0 as latest. I am unable to pull the latest version 0.5.1 .
<img width="1332" alt="Screen Shot 2020-06-24 at 1 07 12 PM" src="https://user-images.githubusercontent.com/6789328/85622374-a06b9a00-b61b-11ea-9256-b8cb3df8ae4a.png">

When I try to pull the latest version I see this error on my terminal 
[!] CocoaPods could not find compatible versions for pod "DBDebugToolkit":
  In Podfile:
    DBDebugToolkit (~> 0.5.1)

None of your spec sources contain a spec satisfying the dependency: `DBDebugToolkit (~> 0.5.1)`.

**Comment by gamada-de** [comment]
Hi,
the latest version is now published on the cocoapods spec repo.

Best regards.

**Comment by ankykush** [comment]
thanks
