### ISSUE TITLE
Crash on "db_removeTouchIndicatorWithTouch" if indicatorView is nil

### ISSUE THREAD

**Issue by cerupcat** [dbukowski/DBDebugToolkit#4]
For some reason indicatorView in db_removeTouchIndicatorWithTouch can end up being null and adding a null object to a set will crash. There should be a check prior to adding that it's not nil.

**Comment by dbukowski** [comment]
Hi! Thanks for reporting that! I'm definitely going to take a closer look at it. For now I pushed a new version to both GitHub & Cocoapods with the suggested fix. If you have any tips on reproducing that issue that would be great.
