### ISSUE TITLE
Trouble with view

### ISSUE THREAD

**Issue by Max-Job** [dbukowski/DBDebugToolkit#45]
The same was fixed in other app when I removed NSLogs. This way don't work here.
Have you any ideas how to resolve it?

<img width="586" alt="Снимок экрана 2020-12-10 в 11 51 58" src="https://user-images.githubusercontent.com/58559377/101748952-361db780-3ade-11eb-9457-7a1b0457fe9a.png">

**Comment by gamada-de** [comment]
Topic is to old and will be closed.
