### ISSUE TITLE
App Extension related error

### ISSUE THREAD

**Issue by marcoswmv** [dbukowski/DBDebugToolkit#48]
![Снимок экрана 2021-03-05 в 7 37 55 PM](https://user-images.githubusercontent.com/32042867/110158934-4d70f600-7dea-11eb-9c6d-bdb459b7cdd3.png)

I'm getting this error since I added an target for my app extension to the pod file. Is there any workaround that would allow me to keep using it with this error?

**Comment by gamada-de** [comment]
This has nothing to do with the DBDebugtoolKit
