### ISSUE TITLE
How to show menu or widget programmatically?

### ISSUE THREAD

**Issue by andreyreddit** [dbukowski/DBDebugToolkit#5]
I have multiple debugging libraries in the project and I can't find API to initialize manually parts of the app by QA or other engineers.

**Comment by andreyreddit** [comment]
Even sharedInstance is private and you can't do anything.

**Comment by 0111b** [comment]
Hi @andreyreddit 
I think you can subclass DBDebugToolkitTrigger and use delegate to present this toolkit.
Also you can use custom actions to cooperate with other tools

**Comment by dbukowski** [comment]
Hello @andreyreddit,
I just released version 0.2.0 which provides new convenience methods to show the menu, widget and the `UIDebuggingInformationOverlay` programmatically.
