### ISSUE TITLE
App crash if call NSURLSessionConfiguration before DBDebgToolkit.setup() 

### ISSUE THREAD

**Issue by qkzhu** [dbukowski/DBDebugToolkit#56]
version `0.7.0` crash if any network request triggered before `DBDebugToolkit.setup()`:
> file name: NSURLSessionConfiguration+DBURLProtocol.m
[originalProtocols insertObject:DBNetworkURLProtocolClass atIndex:0];
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

The cause is from the update for issue #50. 

In this update, `NSURLSessionConfiguration+DBURLProtocol.m`:
`[originalProtocols insertObject:DBNetworkURLProtocolClass atIndex:0]`

1. `NSURLSessionConfiguration`'s swizzing happens in `+(void)load`, which is when app starts, even before `appDelegate.didFinishLaunchingWithOptions`.
2. `DBNetworkURLProtocolClass` is initialised in `+ (void)initialize`, which will be triggered by `DBDebgToolkit.setup()`.

So, without executing `DBDebgToolkit.setup()`, `DBNetworkURLProtocolClass` will **not** be initialed, and it will be crashed.

We can use `load` to initialise `DBNetworkURLProtocolClass`, or ask user to run `DBDebgToolkit.setup()` before any network calls that involved `NSURLSessionConfiguration`.

**Comment by qkzhu** [comment]
@m1entus

**Comment by m1entus** [comment]
@qkzhu Forgot to apply fix for this was because i thught that this repo is dead actually and already forked it on our internal one. Here is patch that fix that issue:
<img width="1243" alt="Zrzut ekranu 2022-02-3 o 10 13 21" src="https://user-images.githubusercontent.com/1565368/152313682-980a30dd-972e-410f-89c0-117d20e8c994.png">

**Comment by qkzhu** [comment]
LOL, yeah, it looks dead. @m1entus, thanks, I just copied it over to this PR.
