### ISSUE TITLE
Measuring CPU, Memory and FPS on main thread is not accurate

### ISSUE THREAD

**Issue by LeoNatan** [dbukowski/DBDebugToolkit#7]
Hello,

Very nice toolkit!
One thing I’ve noticed is, the more blocked the main thread is, the less accurate the measurements are. Especially the FPS measurement, it is possible to lose entire CPU spikes (60 fps -> quick ramp up of a CPU spike for some time -> 60 fps). I have found that the CADisplayLink strategy for measuring FPS is not the most accurate if main thread spikes exist.

One challenge with moving the measurements to a background queue is updating the widget and table view. This can be solved by using a `CATextLayer` to update the text in a background queue (`CALayer` and `CATransation` are thread safe as of iOS 4).

Would you be interested in a PR that accomplishes this?

**Comment by dbukowski** [comment]
Hello @LeoNatan!

Thank you very much for the kind words about the library and the effort to make it better! It would be great if you could open a PR with this change, as I am currently working in my spare time on a new big feature for DBDebugToolkit :)

**Comment by LeoNatan** [comment]
Great! 👍

I’ll be working on this soon™. I want to make sure everything is safe to access from any thread.

**Comment by gamada-de** [comment]
This issue will be closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem 👍
