### ISSUE TITLE
Invalid Network Table View Management

### ISSUE THREAD

**Issue by LeoNatan** [dbukowski/DBDebugToolkit#9]
In a scenario I can reproduce every time, it seems there is an improper management of the table view’s rows:

> Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (39) must be equal to the number of rows contained in that section before the update (38), plus or minus the number of rows inserted or deleted from that section (1 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

The scenario is go in the Requests screen, and do a scroll to bottom. Then quickly open the debug menu and go in the Network screen. The requests are being updated, and the crash occurs in this method:

```objc
- (void)networkDebugToolkit:(DBNetworkToolkit *)networkToolkit didUpdateRequestAtIndex:(NSInteger)index {
    dispatch_async(dispatch_get_main_queue(), ^{
        DBRequestModel *requestModel = self.networkToolkit.savedRequests[index];
        if (requestModel == self.openedRequest) {
            [self.requestDetailsViewController configureWithRequestModel:requestModel];
        }
        [self updateRequests];
        NSInteger updatedRequestIndex = [self.filteredRequests indexOfObject:requestModel];
        if (updatedRequestIndex != NSNotFound) {
            [self.tableView reloadRowsAtIndexPaths:@[ [NSIndexPath indexPathForRow:self.filteredRequests.count - 1 - updatedRequestIndex inSection:0] ]
                                  withRowAnimation:UITableViewRowAnimationAutomatic];
        }
    });
}
```

**Comment by LeoNatan** [comment]
One easy solution 😁 is to just `[self.tableView reloadData];` in case an exception is thrown.

**Comment by LeoNatan** [comment]
This is due to improper multithreaded handling of the system. The table view is instructed to update, but the array of requests is mutated in a different thread. A simple `dispatch_async(dispatch_get_main_queue(), …` is not good enough.

The solution is not simple at all. A two stage solution needs to be implemented, where at one stage, all multithreaded requests are handled in a thread safe manner (currently not the case) and then propagate these changes, again, in a thread safe manner, to an object that can then dispatch tableview updates. For UI, the second stage objects must be only mutated on the main thread, so that all these mutations are then propagated safely to the table view.

An example of this strategy is how Core Data manages its contexts. If you have a background queue context which modifies the store, changes are later propagated to a main queue context that is responsible for pushing the UI. Background contexts cannot be used to push UI, obviously.

Unfortunately, I don’t have time to implement this change right now. I will be using the debug toolkit for a project, but I have different needs; I will only be using the data parts of the project, so all UI be going down. As such, the changes I will be making to the library do not suit the current general purpose of the debug toolkit. If I have time later, I may propose a solution of the strategy above.

**Comment by dbukowski** [comment]
Hi, I finally found time to work on that issue. It really was very easy to reproduce. Thanks for detailed description and suggestions on how to fix that. It should be fixed in the newest version - v. 0.3.1.
